import "./globals.css";
import Meta from "@/components/meta";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Meta />
      <body>{children}</body>
    </html>
  );
}
